# Generated by Django 6.0 on 2025-12-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("pdf", "Bulletin (PDF)"), ("image", "Carte (Image)")],
                        max_length=10,
                    ),
                ),
                ("fichier", models.FileField(upload_to="uploads/")),
                ("stock", models.PositiveIntegerField(default=0)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
