# Generated by Django 6.0 on 2025-12-22 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("description", models.TextField()),
                ("description_courte", models.CharField(blank=True, max_length=300)),
                (
                    "prix",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "type_produit",
                    models.CharField(
                        choices=[
                            ("pdf", "Bulletin (PDF)"),
                            ("image", "Carte (Image)"),
                            ("service", "Service"),
                            ("physique", "Produit Physique"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True, null=True, upload_to="produits/fichiers/"
                    ),
                ),
                (
                    "image_principale",
                    models.ImageField(blank=True, upload_to="produits/images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=True)),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits.categorie",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
