# Generated by Django 6.0 on 2025-12-22 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name="produit",
            old_name="date_ajout",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="produit",
            old_name="titre",
            new_name="nom",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="type",
        ),
        migrations.AddField(
            model_name="produit",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produits_crees",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produit",
            name="description_courte",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="produit",
            name="image_principale",
            field=models.ImageField(blank=True, upload_to="produits/images/"),
        ),
        migrations.AddField(
            model_name="produit",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="produit",
            name="prix",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="produit",
            name="type_produit",
            field=models.CharField(
                choices=[
                    ("pdf", "Bulletin (PDF)"),
                    ("image", "Carte (Image)"),
                    ("service", "Service"),
                    ("physique", "Produit Physique"),
                ],
                default="pdf",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="produit",
            name="fichier",
            field=models.FileField(
                blank=True, null=True, upload_to="produits/fichiers/"
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="produits.categorie",
            ),
        ),
    ]
