# Generated by Django 6.0 on 2025-12-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0002_categorie_rename_date_ajout_produit_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="slug",
            field=models.SlugField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
